# Generated by Django 3.2.9 on 2021-12-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='header',
            new_name='title',
        ),
    ]
